package utils;

public class Consts {
    public static final String HOST = "rabbitmq";
    public static String ADD_FOOTBALL_QUEUE = "ADD_FOOTBALL_QUEUE";
    public static String ADD_BASKETBALL_QUEUE = "ADD_BASKETBALL_QUEUE";
    public static String GET_FACILITY_QUEUE = "GET_FACILITY_QUEUE";
    public static String GET_ALL_FACILITY_QUEUE = "GET_ALL_FACILITY_QUEUE";
    public static String REMOVE_FACILITY_QUEUE = "REMOVE_FACILITY_QUEUE";
    public static String UPDATE_FOOTBALL_FACILITY_QUEUE = "UPDATE_FOOTBALL_FACILITY_QUEUE";
    public static String UPDATE_BASKETBALL_FACILITY_QUEUE = "UPDATE_BASKETBALL_FACILITY_QUEUE";

    public static String ADD_CLIENT_QUEUE = "ADD_CLIENT_QUEUE";
    public static String UPDATE_CLIENT_QUEUE = "UPDATE_CLIENT_QUEUE";
    public static String REMOVE_CLIENT_QUEUE = "REMOVE_CLIENT_QUEUE";
    public static String BLOCK_CLIENT_QUEUE = "BLOCK_CLIENT_QUEUE";
    public static String UNBLOCK_CLIENT_QUEUE = "UNBLOCK_CLIENT_QUEUE";
    public static String GET_CLIENT_QUEUE = "GET_CLIENT_QUEUE";
    public static String GET_ALL_CLIENT_QUEUE = "GET_ALL_CLIENT_QUEUE";

    public static String GET_RESERVATION_QUEUE = "GET_RESERVATION_QUEUE";
    public static String GET_ALL_RESERVATIONS_QUEUE = "GET_ALL_RESERVATIONS_QUEUE";
    public static String GET_CLIENT_RESERVATIONS_QUEUE = "GET_CLIENT_RESERVATIONS_QUEUE";
    public static String REMOVE_RESERVATION_QUEUE = "REMOVE_RESERVATION_QUEUE";
    public static String CANCEL_RESERVATION_QUEUE = "CANCEL_RESERVATION_QUEUE";
    public static String MAKE_RESERVATION_QUEUE = "MAKE_RESERVATION_QUEUE";
}
